/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.senac.biblioteca.swing;

import com.senac.biblioteca.bean.Livro;
import com.senac.biblioteca.infra.UtilTela;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ruans
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanePrincipal = new javax.swing.JDesktopPane();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemMenuImprimir = new javax.swing.JMenuItem();
        itemMenuSair = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        itemMenuCadastrarUsuario = new javax.swing.JMenuItem();
        itemMenuGerenciarUsuarios = new javax.swing.JMenuItem();
        menuLivros = new javax.swing.JMenu();
        itemMenuCadastrarLivros = new javax.swing.JMenuItem();
        itemMenuCadastrarCategoria = new javax.swing.JMenuItem();
        itemMenuGerenciarLivros = new javax.swing.JMenuItem();
        menuEmprestimo = new javax.swing.JMenu();
        itemMenuNovoEmprestimo = new javax.swing.JMenuItem();
        itemMenuDevolucaoEmprestimo = new javax.swing.JMenuItem();
        itemMenuEmprestimos = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemMenuSobre = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Biblioteca ROS");

        desktopPanePrincipal.setBackground(new java.awt.Color(204, 204, 204));
        desktopPanePrincipal.setForeground(new java.awt.Color(204, 204, 204));
        desktopPanePrincipal.setPreferredSize(new java.awt.Dimension(760, 550));
        getContentPane().add(desktopPanePrincipal, java.awt.BorderLayout.CENTER);

        menuArquivo.setText("Arquivo");

        itemMenuImprimir.setText("Imprimir");
        menuArquivo.add(itemMenuImprimir);

        itemMenuSair.setText("Sair");
        itemMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemMenuSairMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemMenuSairMouseExited(evt);
            }
        });
        itemMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(itemMenuSair);

        jMenuBarPrincipal.add(menuArquivo);

        menuUsuarios.setText("Gerenciar Usuários");

        itemMenuCadastrarUsuario.setText("Cadastrar Usuário");
        itemMenuCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastrarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemMenuCadastrarUsuario);

        itemMenuGerenciarUsuarios.setText("Gerenciar Usuários");
        itemMenuGerenciarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuGerenciarUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemMenuGerenciarUsuarios);

        jMenuBarPrincipal.add(menuUsuarios);

        menuLivros.setText("Gerenciars Livros");

        itemMenuCadastrarLivros.setText("Cadastrar Livro");
        itemMenuCadastrarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastrarLivrosActionPerformed(evt);
            }
        });
        menuLivros.add(itemMenuCadastrarLivros);

        itemMenuCadastrarCategoria.setText("Cadastrar Categoria");
        itemMenuCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastrarCategoriaActionPerformed(evt);
            }
        });
        menuLivros.add(itemMenuCadastrarCategoria);

        itemMenuGerenciarLivros.setText("Gerenciar Livros");
        itemMenuGerenciarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuGerenciarLivrosActionPerformed(evt);
            }
        });
        menuLivros.add(itemMenuGerenciarLivros);

        jMenuBarPrincipal.add(menuLivros);

        menuEmprestimo.setText("Empréstimos");

        itemMenuNovoEmprestimo.setText("Novo Empréstimo");
        menuEmprestimo.add(itemMenuNovoEmprestimo);

        itemMenuDevolucaoEmprestimo.setText("Devolução ");
        menuEmprestimo.add(itemMenuDevolucaoEmprestimo);

        itemMenuEmprestimos.setText("Empréstimos");
        itemMenuEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuEmprestimosActionPerformed(evt);
            }
        });
        menuEmprestimo.add(itemMenuEmprestimos);

        jMenuBarPrincipal.add(menuEmprestimo);

        menuAjuda.setText("Ajuda");

        itemMenuSobre.setText("Sobre");
        itemMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(itemMenuSobre);

        jMenuBarPrincipal.add(menuAjuda);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBarPrincipal.add(menuSair);

        setJMenuBar(jMenuBarPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        //Ao clicar no botão, dispara o evento de sair da aplicação.           
         System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    private void itemMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMenuSairMouseClicked
     
    }//GEN-LAST:event_itemMenuSairMouseClicked

    private void itemMenuSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMenuSairMouseExited
        
    }//GEN-LAST:event_itemMenuSairMouseExited

    private void itemMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSairActionPerformed
        // Usuário clica em YES para finalizar a aplicação:
       if(JOptionPane.showConfirmDialog(this, "Deseja realmente sair?", "Sair - Sistema Biblioteca ROS", WIDTH, 3) == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_itemMenuSairActionPerformed

    private void itemMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSobreActionPerformed
        // TODO add your handling code here:
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_itemMenuSobreActionPerformed

    private void itemMenuCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        CadastrarUsuario cadastrar = new CadastrarUsuario();
        desktopPanePrincipal.add(cadastrar);
        cadastrar.setVisible(true);
    }//GEN-LAST:event_itemMenuCadastrarUsuarioActionPerformed

    private void itemMenuCadastrarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastrarLivrosActionPerformed
            // TODO add your handling code here:

        UtilTela.abreTela(this, new CadastrarLivro());
    }//GEN-LAST:event_itemMenuCadastrarLivrosActionPerformed

    public void adicionaJIF(JInternalFrame jif){
        desktopPanePrincipal.add(jif);
    }

    
    private void itemMenuGerenciarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuGerenciarLivrosActionPerformed
        
        UtilTela.abreTela(this, new GerenciarLivros(this));
    }//GEN-LAST:event_itemMenuGerenciarLivrosActionPerformed

    private void itemMenuCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastrarCategoriaActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_itemMenuCadastrarCategoriaActionPerformed

    private void itemMenuGerenciarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuGerenciarUsuariosActionPerformed
        // TODO add your handling code here:
        
//        GerenciarUsuarios gerenciar = new GerenciarUsuarios(this);
//        desktopPanePrincipal.add(gerenciar);
//        gerenciar.setVisible(true);
        UtilTela.abreTela(this, new GerenciarUsuarios(this));
    }//GEN-LAST:event_itemMenuGerenciarUsuariosActionPerformed

    private void itemMenuEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuEmprestimosActionPerformed
        // TODO add your handling code here:
        UtilTela.abreTela(this, new Emprestimos(this));
    }//GEN-LAST:event_itemMenuEmprestimosActionPerformed

    
    public void moveToFront(JInternalFrame jif){
        desktopPanePrincipal.moveToFront(jif);        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPanePrincipal;
    private javax.swing.JMenuItem itemMenuCadastrarCategoria;
    private javax.swing.JMenuItem itemMenuCadastrarLivros;
    private javax.swing.JMenuItem itemMenuCadastrarUsuario;
    private javax.swing.JMenuItem itemMenuDevolucaoEmprestimo;
    private javax.swing.JMenuItem itemMenuEmprestimos;
    private javax.swing.JMenuItem itemMenuGerenciarLivros;
    private javax.swing.JMenuItem itemMenuGerenciarUsuarios;
    private javax.swing.JMenuItem itemMenuImprimir;
    private javax.swing.JMenuItem itemMenuNovoEmprestimo;
    private javax.swing.JMenuItem itemMenuSair;
    private javax.swing.JMenuItem itemMenuSobre;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuEmprestimo;
    private javax.swing.JMenu menuLivros;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
